import os
import re
import base64
import logging
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

# Configure basic logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Load environment variables
load_dotenv()

from config import NOTION_TOKEN, COMPLAINTS_DATABASE_ID, VENDORS_DATABASE_ID
from services import (
    parse_complaint, decide_status, create_complaint_row, 
    check_approvals, get_vendor, check_resolutions, mark_resolution_email_sent,
    describe_image_issue
)
from dispatch.email import notify_vendor, notify_student_resolved
from fastapi.staticfiles import StaticFiles

app = FastAPI(title="Hostel Maintenance API")

# Mount static directory for background images and assets
app.mount("/static", StaticFiles(directory="static"), name="static")

# Add CORS middleware to allow cross-origin requests from the frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

from typing import Optional
class ComplaintRequest(BaseModel):
    room: str
    text: str
    email: Optional[str] = None

class ImageAnalysisRequest(BaseModel):
    image: str
    mime_type: Optional[str] = "image/jpeg"
    api_key: Optional[str] = None
    file_name: Optional[str] = None

class ApiKeyRequest(BaseModel):
    api_key: str

# In-memory database to store complaints temporarily so you can view them on the web
complaints_db = []
# Set to track IDs of already dispatched complaints to prevent duplicate emails
dispatched_records = set()

from fastapi.responses import FileResponse

@app.get("/")
async def serve_frontend():
    """
    Serve the frontend HTML directly from FastAPI to avoid 'file://' security blocks in the browser.
    """
    return FileResponse("index.html")

@app.post("/save-gemini-key")
async def save_gemini_key(req: ApiKeyRequest):
    key = req.api_key.strip()
    os.environ["GEMINI_API_KEY"] = key
    try:
        env_content = ""
        if os.path.exists(".env"):
            with open(".env", "r", encoding="utf-8") as f:
                env_content = f.read()
        if "GEMINI_API_KEY=" in env_content:
            env_content = re.sub(r"GEMINI_API_KEY=.*", f"GEMINI_API_KEY={key}", env_content)
        else:
            env_content += f"\nGEMINI_API_KEY={key}\n"
        with open(".env", "w", encoding="utf-8") as f:
            f.write(env_content.strip() + "\n")
    except Exception as e:
        logger.warning(f"Could not save key to .env file: {e}")
    return {"success": True, "message": "API key configured successfully"}

@app.post("/analyze-image")
async def analyze_image_endpoint(req: ImageAnalysisRequest):
    """
    Accepts a base64 encoded image and returns a concise problem description generated by Gemini AI.
    """
    load_dotenv(override=True)
    logger.info("Received image analysis request...")
    try:
        raw_image_data = req.image
        if not raw_image_data:
            return {"success": False, "error": "No image data provided."}

        mime_type = req.mime_type or "image/jpeg"
        # If it's a data URL like "data:image/png;base64,iVBORw..."
        if "base64," in raw_image_data:
            header, base64_str = raw_image_data.split("base64,", 1)
            mime_match = re.search(r"data:([^;]+);", header)
            if mime_match:
                mime_type = mime_match.group(1)
        else:
            base64_str = raw_image_data

        image_bytes = base64.b64decode(base64_str)
        result = describe_image_issue(
            image_bytes=image_bytes, 
            mime_type=mime_type, 
            api_key=req.api_key,
            file_name=req.file_name
        )
        return result
    except Exception as e:
        logger.error(f"Error analyzing image: {e}")
        return {"success": False, "error": f"Failed to analyze image: {str(e)}"}

@app.get("/complaints")
async def view_complaints():
    """
    Visit http://127.0.0.1:8080/complaints in your browser to see all submitted complaints!
    """
    return complaints_db

@app.post("/submit-complaint")
async def submit_complaint(complaint: ComplaintRequest):
    load_dotenv(override=True)
    logger.info(f"\n================================")
    logger.info(f"NEW COMPLAINT RECEIVED!")
    logger.info(f"Room: {complaint.room}")
    logger.info(f"Email: {complaint.email}")
    logger.info(f"Text: {complaint.text}")
    logger.info(f"================================\n")

    try:
        notion_token = os.getenv("NOTION_TOKEN")
        complaints_db_id = os.getenv("COMPLAINTS_DATABASE_ID")
        vendors_db_id = os.getenv("VENDORS_DATABASE_ID")

        # 1. Parse via Gemini API (or heuristic fallback)
        parsed_data = parse_complaint(complaint.text)
        category = parsed_data.get("category", "Other")
        urgency = parsed_data.get("urgency", "Medium")
        
        # Determine room location: prioritize explicitly provided room, fallback to AI extraction
        room_block = complaint.room.strip() if complaint.room and complaint.room.strip() else (parsed_data.get("room_block") or "Unspecified")

        # 2. Decide the initial status (e.g. 'Pending Approval' vs fast-tracked 'Auto-Approved')
        status = decide_status(urgency, category)
        
        # 3. Look up vendor in the Vendors Notion database or default vendor directory
        vendor_info = get_vendor(category, notion_token, vendors_db_id)
        vendor_name = vendor_info.get("name", "Facility Maintenance")
        vendor_email = vendor_info.get("email")

        # 4. Compile the payload
        row_data = {
            "room_block": room_block,
            "raw_text": complaint.text,
            "urgency": urgency,
            "category": category,
            "status": status,
            "vendor_assigned": vendor_name,
            "student_email": complaint.email
        }

        # 5. Create the row in the Notion database if configured, or save locally
        if notion_token and complaints_db_id:
            result = create_complaint_row(row_data, notion_token, complaints_db_id)
            record_id = result.get("notion_id", f"local_id_{len(complaints_db) + 1}")
        else:
            logger.info("Notion credentials not set - recorded complaint in local memory store.")
            record_id = f"local_id_{len(complaints_db) + 1}"
        
        # Save to temporary in-memory database to show on the webpage / local testing
        record = row_data.copy()
        record["id"] = record_id
        record["vendor_email"] = vendor_email
        complaints_db.append(record)

        return {
            "success": True,
            "parsed_data": {
                "category": category,
                "urgency": urgency,
                "room_block": room_block,
                "status": status,
                "vendor_assigned": vendor_name
            }
        }

    except Exception as e:
        logger.error(f"Error processing complaint: {type(e).__name__} - {str(e)}")
        return {
            "success": False,
            "error": f"Error processing complaint: {str(e)}"
        }

@app.post("/run-dispatch")
async def run_dispatch():
    """
    Checks Notion / local memory for approved complaints and resolution notifications.
    """
    notion_token = os.getenv("NOTION_TOKEN")
    complaints_db_id = os.getenv("COMPLAINTS_DATABASE_ID")
    vendors_db_id = os.getenv("VENDORS_DATABASE_ID")

    approved_complaints = []
    
    # 1. Retrieve Warden-approved complaints from Notion if configured
    if notion_token and complaints_db_id:
        approved_complaints = check_approvals(notion_token, complaints_db_id)
    
    # 2. Also grab any fast-tracked "Auto-Approved" complaints from local DB
    for c in complaints_db:
        if c.get("status") == "Auto-Approved" and c.get("id") not in dispatched_records:
            if not any(ac.get("id") == c.get("id") for ac in approved_complaints):
                approved_complaints.append(c)

    dispatched_count = 0
    for complaint in approved_complaints:
        complaint_id = complaint.get("id")
        
        if complaint_id in dispatched_records:
            continue
            
        vendor_email = complaint.get("vendor_email")
        if not vendor_email:
            category = complaint.get("category", "Other")
            vendor_info = get_vendor(category, notion_token, vendors_db_id)
            vendor_email = vendor_info.get("email") or "vendor@hostel.local"
        
        logger.info(f"Dispatching notification for complaint {complaint_id} to vendor ({vendor_email})...")
        notify_result = notify_vendor(vendor_email, complaint)
        
        if notify_result.get("success"):
            logger.info(f"Vendor notification successful for complaint {complaint_id}")
            dispatched_records.add(complaint_id)
            
            if notion_token:
                from services import update_complaint_status
                update_complaint_status(complaint_id, "Dispatched", notion_token)
            
            for db_record in complaints_db:
                if db_record.get("id") == complaint_id:
                    db_record["status"] = "Dispatched"
                    
            dispatched_count += 1
        else:
            logger.warning(f"Vendor notification not sent: {notify_result.get('message')}")

    # ==========================================
    # RESOLUTION NOTIFICATION (Student Email)
    # ==========================================
    resolved_count = 0
    resolved_complaints = []
    
    if notion_token and complaints_db_id:
        resolved_complaints = check_resolutions(notion_token, complaints_db_id)
        
    for c in complaints_db:
        if c.get("status") == "Resolved" and not c.get("resolution_email_sent"):
            if not any(rc.get("id") == c.get("id") for rc in resolved_complaints):
                resolved_complaints.append(c)
    
    for complaint in resolved_complaints:
        complaint_id = complaint.get("id")
        student_email = complaint.get("student_email")
        
        if not student_email:
            continue
            
        logger.info(f"Sending resolution notification to student {student_email}...")
        notify_result = notify_student_resolved(student_email, complaint)
        
        if notify_result.get("success"):
            if notion_token:
                mark_resolution_email_sent(complaint_id, notion_token)
            for db_record in complaints_db:
                if db_record.get("id") == complaint_id:
                    db_record["resolution_email_sent"] = True
            resolved_count += 1

    return {
        "message": f"Successfully dispatched {dispatched_count} complaints to vendors. Sent {resolved_count} resolution emails."
    }

# ==========================================
# BACKGROUND AUTOMATION
# ==========================================
import asyncio

async def auto_dispatch_loop():
    """
    Background worker that checks for approvals and resolutions every 30 seconds.
    """
    while True:
        try:
            await run_dispatch()
        except Exception as e:
            logger.debug(f"Auto dispatch loop: {e}")
            
        await asyncio.sleep(30)

@app.on_event("startup")
async def startup_event():
    """
    When FastAPI starts, spawn the auto_dispatch_loop in the background.
    """
    logger.info("Starting background auto-dispatch scanner (checks every 30s)...")
    asyncio.create_task(auto_dispatch_loop())

